import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const customers = [
    { code: 'AA', name: 'AA, UD.' },
    { code: 'AAI', name: 'ALAMI AGRO INDUSTRY, PT' },
    { code: 'AB', name: 'AGRO ABADI, UD' },
    { code: 'ABP', name: 'AMAN BUANA PUTERA, PT' },
    { code: 'ABS', name: 'ANDAL BENTARA SAMUDERA' },
    { code: 'AF', name: 'UD ALFAIZAN' },
    { code: 'AFI', name: 'ALITOA FIRDAUS INDUSTRY, PT' },
    { code: 'AFZAL', name: 'CAHAYA MAJU BERSAMA, CV.' },
    { code: 'AG', name: 'PT. AGROSARI SENTRAPRIMA' },
    { code: 'AGM', name: 'PT. ASNAFF GROUP MANDIRI' },
    { code: 'AGRIM', name: 'JASUM JAYA, PT' },
    { code: 'AGRO', name: 'CV.AGRO MAKMUR JAYA' },
    { code: 'AI', name: 'PT. ASNAFF INTERNATIONAL' },
    { code: 'AK', name: 'MULTI KARYA, CV' },
    { code: 'AL-I', name: 'AL-IKHWAN TRADING CV' },
    { code: 'ALS', name: 'CV.ALAMSYAH' },
    { code: 'AM', name: 'PERINDUSTRIAN KAYU ASIA MUJUR, PT' },
    { code: 'AMJ', name: 'ANUGERAH MAS JAYA, PT' },
    { code: 'AMS', name: 'PT.ADIMULIA SARIMAS INDONESIA' },
    { code: 'ANG', name: 'PT.ASNAFF GROUP MANDIRI' },
    { code: 'AP', name: 'ANEKA PLASTIK' },
    { code: 'APA', name: 'PT. AGRO PERKASA ABADI' },
    { code: 'ARCI', name: 'UD.ARCI' },
    { code: 'ARI', name: 'ALAM RAYA INDOMIN, PT' },
    { code: 'ARR', name: 'ALAM RAYA RATTAN, PT' },
    { code: 'ASA', name: 'CV. ASA INDONESIA' },
    { code: 'ASM', name: 'PT. ADIMULIA SARI MAS INDUSTRI' },
    { code: 'ASW', name: 'PT. ASIA SAKTI WAHID FOOD MANUFACTURE' },
    { code: 'BAJ', name: 'BANDUNG ASA JAYA, PT' },
    { code: 'BD', name: 'PT. BELAWANDELI CHEMICAL INDUSTRY' },
    { code: 'BIN', name: 'PT.BUMI INDAWA NIAGA' },
    { code: 'BKLM', name: 'BINA KARYA LOGAM MANDIRI, PT' },
    { code: 'BM', name: 'BERUANG MAS, PT.' },
    { code: 'BPM', name: 'BUMI PERKASA MAKMUR, PT.' },
    { code: 'BPN', name: 'PT.BERKAT PINANG NUSANTARA' },
    { code: 'BTJ', name: 'BERKAT TIMUR JAYA ,PT' },
    { code: 'CI', name: 'PT. CANANG INDAH INDUSTRI PARTICLEBOARD' },
    { code: 'CII', name: 'PT. CANANG INDAH INDUSTRI PARTICLE BOARD' },
    { code: 'CIP', name: 'PT.CANANG INDAH INDUSTRI PARTICLE BOARD' },
    { code: 'CKI', name: 'CITRA KENCANA INDUSTRI,PT' },
    { code: 'CP', name: 'PT. CIPTA  PRIMA INTERWOODS DEVELOPMENT INDUSTRY' },
    { code: 'CRN', name: 'PT. CHANCE RIMBA NUSANTARA' },
    { code: 'CSBJ', name: 'CIPTASARANA BUANA JAYA,PT' },
    { code: 'DEWI', name: 'GROWTH ASIA, PT' },
    { code: 'EGM', name: 'EXPRESS GLOBE MARKETING, PT.' },
    { code: 'ELVI', name: 'BUKIT KEMBANG JAYA, CV.' },
    { code: 'EQ', name: 'EQUATOR, CV.' },
    { code: 'GA', name: 'GROWTH ASIA,PT' },
    { code: 'GE', name: 'GANESHA EXIM, PT.' },
    { code: 'GLOBAL', name: 'GLOBAL QUALITY, PT' },
    { code: 'GQC', name: 'PT. GLOBAL QUALITY COMMODITY' },
    { code: 'GRN', name: 'GREEN RIVER NUSANTARA, PT' },
    { code: 'GSM', name: 'PT.GREENEX SUMATERA MANDIRI' },
    { code: 'HAI', name: 'HASIL ALAM INDO, PT' },
    { code: 'HC', name: 'HARVARD COCOPRO,PT' },
    { code: 'HM', name: 'CV. HARAMAS' },
    { code: 'HU', name: 'HIBA UTAMA' },
    { code: 'IC', name: 'INDO CAFCO, PT' },
    { code: 'IEI', name: 'PT.INDO EMERALD IMPEX' },
    { code: 'IMCO', name: 'IMCO, PT' },
    { code: 'INA', name: 'PT.INDUSTRI AGRIBISNIS INDONESIA' },
    { code: 'INDOCRAFT', name: 'INDOCRAFT AND NATURALS, PT' },
    { code: 'IP', name: 'INDOPAK, PT.' },
    { code: 'IPTRD', name: 'PT.INDUSTRI PLYWOOD TJIPTA RIMBA DJAJA' },
    { code: 'IUI', name: 'PT. IHSAN ULLAH INDONESIA' },
    { code: 'JF', name: 'MEMON INTERNATIONAL, PT.' },
    { code: 'JFI', name: 'JAFFARINDO INDONESIA, PT' },
    { code: 'JL', name: 'AURORA BAKTI, CV.' },
    { code: 'KA', name: 'KARYA AGUNG LESTARI JAYA, PT' },
    { code: 'KAJECO', name: 'PT.KAJECO INDONESIA' },
    { code: 'KARUNIA', name: 'KARUNIA ALAM PRIMA SEJATI,PT' },
    { code: 'KI', name: 'KARYA INDRA,CV' },
    { code: 'KJ', name: 'PT. KELAMBIR JAYA' },
    { code: 'KLJ', name: 'PT.KLAMBIR JAYA' },
    { code: 'KMPP', name: 'PT.KARYA MANDIRI PRATAMA PLASINDO' },
    { code: 'KMS', name: 'KELUARGA MITRATANI SEJAHTERA, PT.' },
    { code: 'KP', name: 'KARYA PLASINDO, PT' },
    { code: 'KS', name: 'KEMASINDO SUMATERA, PT' },
    { code: 'KYI', name: 'PT. KIYAD INDUSTRY' },
    { code: 'L', name: 'LAIN LAIN, PT' },
    { code: 'LAIN', name: 'LAINNYA' },
    { code: 'LDC', name: 'PT. LOUIS DREYFUS COMMODITIES INDONESIA' },
    { code: 'LDCT', name: 'PT. LDC TRADING INDONESIA' },
    { code: 'LINA', name: 'LINA NARTO' },
    { code: 'LISE', name: 'BAJA UTAMA, PT' },
    { code: 'LU', name: 'PT. LAUT UNITED' },
    { code: 'MA', name: 'MAPTRASCO' },
    { code: 'MARU', name: 'MARU, PT' },
    { code: 'MB', name: 'CV.MULIA BERKAH' },
    { code: 'MCP', name: 'MARIENDAL CIPTA PRIMA, PT' },
    { code: 'MDI', name: 'MARK DYNAMICS INDONESIA, PT' },
    { code: 'MDS', name: 'PT.MULTI DJASA SARANA' },
    { code: 'MESTIKA', name: 'UD, MESTIKA PINANG' },
    { code: 'METCO', name: 'PT.METCO INDONESIA' },
    { code: 'MJ', name: 'MUDA JAYA, UD.' },
    { code: 'MJS', name: 'PT. MULTI JASA SARANA' },
    { code: 'MK', name: 'MULIA KARYA, CV' },
    { code: 'MKW', name: 'MULYO KAWI WIJOYO, PT' },
    { code: 'MP', name: 'PT. MAHA PUTRA SAKTI GRAHA' },
    { code: 'MS', name: 'CV. MANDIRI SEJAHTERA' },
    { code: 'MSC', name: 'MEDITERRANEAN SHIPPING COMPANY SA' },
    { code: 'MSI', name: 'PT.MEDAN SUGAR INDUSTRY' },
    { code: 'MTG', name: 'MEDIKA TAHTA GLORI, PT' },
    { code: 'MTP', name: 'PT. METROPOLE PURNAMA CITRA' },
    { code: 'MULYA', name: 'MULYA, CV.' },
    { code: 'NSC', name: 'PT. NASINDOSEJAHTERA CEMERLANG' },
    { code: 'OLAM C', name: 'OLAM INDONESIA, PT.' },
    { code: 'OLAM K', name: 'PT. OLAM INDONESIA' },
    { code: 'OLAM P', name: 'OLAM INDONESIA, PT.' },
    { code: 'PA', name: 'CV.PERMATA MANDIRI' },
    { code: 'PCI', name: 'PT. PAPANDAYAN COCOA INDUSTRIES' },
    { code: 'PJ', name: 'PT. PINANG JAYA SUMATERA' },
    { code: 'PJ-AF', name: 'AFZAL / NOOMAN' },
    { code: 'PJL', name: 'PT. PIGURA JASALINDO' },
    { code: 'PPI', name: 'PACIFIC PALMINDO INDUSTRI,PT' },
    { code: 'PPM', name: 'KARYA AGRO LESTARI, PT.' },
    { code: 'PRAKARSA', name: 'PT.PRAKARSA DHARMA MADUMA' },
    { code: 'PWT', name: 'PACIFIC WORLD TRANS' },
    { code: 'QAR', name: 'CV. QAR HOKY SAMUDRA' },
    { code: 'RAT', name: 'PT.RAFIULLAH BIN AMINA TRADING' },
    { code: 'RCI', name: 'CV.RIAU CAKRA INDONESIA' },
    { code: 'RJ', name: 'CV. RJ SYAUQI ASYRAF' },
    { code: 'RJS', name: 'CV. RJ SATTRIA' },
    { code: 'ROJO', name: 'PT.ROJO CIPTANIAGA KENCANA' },
    { code: 'RP', name: 'PT. ROYAL PACIFIC INDAH INTERNATIONAL' },
    { code: 'RU', name: 'REDIAN UTAMA,CV' },
    { code: 'S/A', name: 'SURYA RIMBA WANA SUBUR, PT.' },
    { code: 'S/S', name: 'SURYA RIMBA WANA SUBUR, PT.' },
    { code: 'SB', name: 'PT. STARA BUMI SURYA' },
    { code: 'SBA', name: 'SARI BAROKAH, CV' },
    { code: 'SBS', name: 'PERKASA ABADI, UD.' },
    { code: 'SC', name: 'SEJATI COCONUT INDUSTRY' },
    { code: 'SCI', name: 'SUD CHEMIE INDONESIA, PT' },
    { code: 'SERASI', name: 'UD. SERASI JAYA' },
    { code: 'SFM', name: 'PT. SINAR LAFINDO MAKMUR' },
    { code: 'SGM', name: 'CV.SINAR GUNUNG MAS JAYA' },
    { code: 'SGMC', name: 'SINAR GUNUNG MAS CEMERLANG, PT' },
    { code: 'SH', name: 'HIBAH UTAMA' },
    { code: 'SJH', name: 'SEJAHTERA, CV.' },
    { code: 'SJL', name: 'PT. SUMATERA JAYA LESTARI' },
    { code: 'SKW', name: 'SEKAWAN, CV.' },
    { code: 'SL', name: 'PT. SIAN LIEP BUMI PERSADA' },
    { code: 'SLE', name: 'STRAIT LINER EXPRESS, PT' },
    { code: 'SLL', name: 'SAMUDRA LAUTAN LUAS' },
    { code: 'SMART', name: 'SMART TBK,PT' },
    { code: 'SMC', name: 'SHAMROCK MANUFACTURING CORPORA, PT.' },
    { code: 'SMS', name: 'PT.SUMBER MITRA SARANA' },
    { code: 'STI', name: 'PT. SAMPURNA TRADEINDO' },
    { code: 'TGH', name: 'CV.TEGUH TETAP JAYA' },
    { code: 'TI', name: 'PT.TIMBERLAND INDUSTRI' },
    { code: 'TMEL', name: 'PT.TRANSLINDO MALAKA EXPRESS LINE' },
    { code: 'TMN', name: 'PT.TIGA MUTIARA NUSANTARA' },
    { code: 'TPJB', name: 'PT.TUNASRINDO PRIMA JAYA BERSAMA' },
    { code: 'TRANS', name: 'TRANSLINDO MALAKA EXPRESS LINE' },
    { code: 'TRD', name: 'PT. TJIPTA RIMBA DJAJA' },
    { code: 'TRUVA', name: 'TRUVA PASIFIK, PT' },
    { code: 'TSP', name: 'PT. TAHTA SAMUDERA PERTIWI' },
    { code: 'TTP', name: 'TONGA TIUR PUTRA, PT.' },
    { code: 'UJ', name: 'UJANG JAYA, CV' },
    { code: 'UJI', name: 'PT. UJANG JAYA INTERNATIONAL' },
    { code: 'UNIBIS', name: 'PT. UNIVERSAL INDOFOOD PRODUCT' },
    { code: 'UR', name: 'CV.USAHA RAJIN' },
    { code: 'URS', name: 'PT. USAHA RAJIN SATTRIA' },
    { code: 'VAL', name: 'PT VALMATIC INDONESIA' },
    { code: 'VIKTORINDO', name: 'VIKTORINDO,PT.' },
    { code: 'VJL', name: 'VIPUL JAYA LESTARI, PT' },
    { code: 'WILLY', name: 'WRP BUANA MULTICORPORA, PT.' },
    { code: 'WIN', name: 'PT.WIN ELECTROINDO HEAT' },
    { code: 'WM', name: 'WIDYA MANDIRI, CV.' },
    { code: 'YUDI', name: 'REDIAN UTAMA, CV' },
];

async function main() {
    console.log(`Start seeding ...`);
    for (const c of customers) {
        const customer = await prisma.customer.upsert({
            where: { code: c.code },
            update: {},
            create: {
                code: c.code,
                name: c.name,
            },
        });
        console.log(`Created customer with id: ${customer.id}`);
    }
    console.log(`Seeding finished.`);
}

main()
    .then(async () => {
        await prisma.$disconnect();
    })
    .catch(async (e) => {
        console.error(e);
        await prisma.$disconnect();
        process.exit(1);
    });
